# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-defer" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "d6a1d673d87b375fdc00b176fc4187da3d08e346239dd552c367082db249f962"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "020a9afacb6afa061b0e873160c382d126122d976764e30b6d70f57a7156feb6"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "03efd957624f2696fd4e9cec0d8a6af3933ff0890a04c34b6d983318aab1cbce"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7424e3c9e5297a147e1a555b6a16d63ae0e0b26e0f6b380248d60b2a91d5a684"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcp-defer"
  desc "Start an MCP stdio server on its first tool call, not at session start; discovery is answered from a cache"
  homepage "https://github.com/stefanahman/mcp-defer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-defer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-defer"]
    end
  end

  # No zap stanza required
end
