# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-defer" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/mcp-defer"]
    end
  end

  version "0.2.1"

  on_macos do
    on_arm do
      sha256 "e0628e2bc1e282633e2af475c4cb5f72165785eb96573d35e024d8b6ea1123ba"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "8a1f6f4b7455e82b23cd810e9480500a864721a50d18c1ed19389e8efae62b82"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "717e8571dfa2bb02c0f6dc5cc102f8b8d09f37a5bac315a0ea1937e77b4e4285"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "65f52a986727394349fa163d05499356c4be52bb75709fcd704cd09301480a2f"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcp-defer"
  desc "Start MCP servers on their first tool call, not at session start"
  homepage "https://github.com/stefanahman/mcp-defer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-defer"

  # No zap stanza required
end
