# This file was generated by GoReleaser. DO NOT EDIT.
cask "mcp-defer" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "1188ce95b13a30682f52a6da43c1b560b431655e566a8228331301a79e967dcb"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "eb25facc15e27a96d36711a8ef058d0f797017fc0958fa9111f97cc3f8ed1e25"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "6a464fe3c7edc303e86f6743133a3a8b6f3eb3f3b30930c059a57b0c6fd59d3d"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "25011d9cb29023c4ef2bf952aa710a08548d35d75e6f2eddd13cd4709b976e28"
      url "https://github.com/stefanahman/mcp-defer/releases/download/v#{version}/mcp-defer_#{version}_linux_amd64.tar.gz"
    end
  end

  name "mcp-defer"
  desc "Start an MCP stdio server on its first tool call, not at session start; discovery is answered from a cache"
  homepage "https://github.com/stefanahman/mcp-defer"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "mcp-defer"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/mcp-defer"]
    end
  end

  # No zap stanza required
end
