# This file was generated by GoReleaser. DO NOT EDIT.
cask "owl" do
  version "0.19.1"

  on_macos do
    on_arm do
      sha256 "121974db26b9cef9cb958b34a1ab2bc357e96ceca5aec14432e37b90b92c138d"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2c084a34943d69847820a890c4c35acd37532af16665749f933bf3471d701369"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "4c3c29af92289c291aeae0035ae47ab520b31ac81909730902e0f6f07f29bc2a"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "b585ce8650111cde11431539de2e0993a380f4714cbb4f430dda57847dfe8545"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "owl"
  desc "TUI of the PRs waiting for your review; one key opens each as a git worktree and a window in tmux, herdr or cmux with Claude Code reviewing inside"
  homepage "https://github.com/stefanahman/owl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "tmux",
    ]

  binary "owl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/owl"]
    end
  end

  # No zap stanza required
end
