# This file was generated by GoReleaser. DO NOT EDIT.
cask "owl" do
  version "0.17.2"

  on_macos do
    on_arm do
      sha256 "bf4a6bfde80f0ada75b313f332cf37a810e6627b7ced78ce5fad646daef0482b"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "b308e3f44409fbf821bc6c6b2fd44ceabe0aeea8f715b824564fa910a5f5bc20"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e268f9982dc0d141f6050a7c19b67d767c87ef5e5046cfd1ed0744f0bbb7cbb3"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "aa6a5b431f75f3655406bc236cd975e5a0d029198b4bbae6523f24ec8b3a5b4e"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "owl"
  desc "TUI of the PRs waiting for your review; one key opens each as a git worktree and a window in tmux, herdr or cmux with Claude Code reviewing inside"
  homepage "https://github.com/stefanahman/owl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "tmux",
    ]

  binary "owl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/owl"]
    end
  end

  # No zap stanza required
end
