# This file was generated by GoReleaser. DO NOT EDIT.
cask "owl" do
  version "0.17.1"

  on_macos do
    on_arm do
      sha256 "735fa31cc57d6223ba5e6d0f02352cba103ed04b0446ef55dc93b8c7226d58b2"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "fd69d290dbc50bb82b316b5eff0dc0d6cc1e3465bfa01742efaf9268ceb8aee3"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "b586f4969de4d016fc4c2b77a414e06fb1ace54af6a43669fa685aa585669a95"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "7b75a94274631364f10ff6c116ddab5ae7d0a66e45118e192c67f1003c2c764f"
      url "https://github.com/stefanahman/owl/releases/download/v#{version}/owl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "owl"
  desc "TUI of the PRs waiting for your review; one key opens each as a git worktree and a window in tmux, herdr or cmux with Claude Code reviewing inside"
  homepage "https://github.com/stefanahman/owl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "tmux",
    ]

  binary "owl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/owl"]
    end
  end

  # No zap stanza required
end
