# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-owl" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "74afe07c9ec7650095221a2cb453faa941a7ec202ed0eaa2dd4b2866f6fbebc4"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "227fff0d696c134f1446a4833cd250192026a853cfeee46ad970d3650ecdad83"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "e540264a0b112fa9eb0e4e06592ddcaead9c2f3636594315ac200b046ff82566"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "11ecccb00ae9a0bd6b949a925482595692e8a611879915b3db6b73755a7f0d18"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-owl"
  desc "TUI of the PRs waiting for your review; one key opens each as a git worktree + tmux window with Claude Code reviewing inside"
  homepage "https://github.com/stefanahman/pr-owl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "tmux",
    ]

  binary "pr-owl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-owl"]
    end
  end

  # No zap stanza required
end
