# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-owl" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "8568cb1d902f0988c6e317ff07423cd02090af47d3495870dc440c6771e81bf1"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "c0d4e3b723bf796dd2dfe776e6adaf523f10fbac2cba9908f506051dda5e67af"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "8317883fbb80b1395852a993371ac5c390aceca21d478b4841603fd113735aa7"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "e15cd68b5f91d93caa494f466b5715808263722863e4cc00ee2db76c3141dda0"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-owl"
  desc "TUI of the PRs waiting for your review; one key opens each as a git worktree + tmux window with Claude Code reviewing inside"
  homepage "https://github.com/stefanahman/pr-owl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "tmux",
    ]

  binary "pr-owl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-owl"]
    end
  end

  # No zap stanza required
end
