# This file was generated by GoReleaser. DO NOT EDIT.
cask "pr-owl" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "2911d7e9fea29275a0b3c3fb15299052c92ca7bba0100b70b793f69fe043a58f"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2ea7410f3da39b31867e0519ff38c821252126d3de414477e4e229161158db02"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "2192d73fe1cba6b911829153dda929c840b766999def23f36b9d6401baeb5c08"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "405d440557d55da7356af0d9d79c3544e6b0d0427be29c82b04052e00587c485"
      url "https://github.com/stefanahman/pr-owl/releases/download/v#{version}/pr-owl_#{version}_linux_amd64.tar.gz"
    end
  end

  name "pr-owl"
  desc "TUI of the PRs waiting for your review; one key opens each as a git worktree + tmux window with Claude Code reviewing inside"
  homepage "https://github.com/stefanahman/pr-owl"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "gh",
      "tmux",
    ]

  binary "pr-owl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/pr-owl"]
    end
  end

  # No zap stanza required
end
