# This file was generated by GoReleaser. DO NOT EDIT.
cask "spaces" do
  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/spaces"]
    end
  end

  version "0.11.1"

  on_macos do
    on_arm do
      sha256 "e753e5db6534b6d68f124165d4780adf10adeeb93e67bbf6391e735d9f039f5a"
      url "https://github.com/stefanahman/spaces/releases/download/v#{version}/spaces_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "f9642c6646067f8b1de3e0ddf324b053e47bc90a983b06e155317c195e7f6c61"
      url "https://github.com/stefanahman/spaces/releases/download/v#{version}/spaces_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "spaces"
  desc "One config for your windows on desktop spaces: tmux sessions, programs, applications"
  homepage "https://github.com/stefanahman/spaces"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "spaces"

  # No zap stanza required
end
