# This file was generated by GoReleaser. DO NOT EDIT.
cask "spaces" do
  version "0.7.1"

  on_macos do
    on_arm do
      sha256 "98b3e04683f6567e30a7008b46c1aaf9b209d8281915adce6863e61a18d572c8"
      url "https://github.com/stefanahman/spaces/releases/download/v#{version}/spaces_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "49656eaba1aa96cd35268c6f8a890175fb92143e0079d3284a1d2aa65a974917"
      url "https://github.com/stefanahman/spaces/releases/download/v#{version}/spaces_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "spaces"
  desc "One config for your windows on desktop spaces: tmux sessions, programs, applications"
  homepage "https://github.com/stefanahman/spaces"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "spaces"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spaces"]
    end
  end

  # No zap stanza required
end
