# This file was generated by GoReleaser. DO NOT EDIT.
cask "spaces" do
  version "0.6.0"

  on_macos do
    on_arm do
      sha256 "c157fa5a9a9a64cdd220313a6c0dfd9035f9b37d28c8c019113d6dbfe8d34064"
      url "https://github.com/stefanahman/spaces/releases/download/v#{version}/spaces_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ac647830b9bd560273014f5570450a0240acd1eb3c55820d466cc95dd9025942"
      url "https://github.com/stefanahman/spaces/releases/download/v#{version}/spaces_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "spaces"
  desc "One config for your windows on desktop spaces: tmux sessions, programs, applications"
  homepage "https://github.com/stefanahman/spaces"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "spaces"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/spaces"]
    end
  end

  # No zap stanza required
end
