# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-spaces" do
  version "0.2.0"

  on_macos do
    on_arm do
      sha256 "05fdc0a28d8005bc65585040b6017aef3447ad5ab618963bebddb95f365aed21"
      url "https://github.com/stefanahman/tmux-spaces/releases/download/v#{version}/tmux-spaces_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "7f7c3e64f448c3e4c258ea201a7fe95d77266a161410e601fb46b7ee968f7545"
      url "https://github.com/stefanahman/tmux-spaces/releases/download/v#{version}/tmux-spaces_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tmux-spaces"
  desc "One config for your tmux sessions on desktop spaces"
  homepage "https://github.com/stefanahman/tmux-spaces"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmux-spaces"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-spaces"]
    end
  end

  # No zap stanza required
end
