# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-spaces" do
  version "0.1.1"

  on_macos do
    on_arm do
      sha256 "e61585f1761cb79b38e8d61e65b81da293604efe339ad450d2ef1e698fddf9cb"
      url "https://github.com/stefanahman/tmux-spaces/releases/download/v#{version}/tmux-spaces_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "ceb47555ea8d22f7a006fda171fd2182cdbef5a2bf4bddff20ba828adb502458"
      url "https://github.com/stefanahman/tmux-spaces/releases/download/v#{version}/tmux-spaces_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tmux-spaces"
  desc "One config for your tmux sessions on desktop spaces"
  homepage "https://github.com/stefanahman/tmux-spaces"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmux-spaces"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-spaces"]
    end
  end

  # No zap stanza required
end
