# This file was generated by GoReleaser. DO NOT EDIT.
cask "tmux-spaces" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "79ed9d8943dd582b48ec8ad7b208cf2b46e83f1dc5fbc669c53f815574f2fc13"
      url "https://github.com/stefanahman/tmux-spaces/releases/download/v#{version}/tmux-spaces_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "3f91c15d9e0d54ca575fec4d8cec247e08512d21c1c42994a0ce8aeb6a34e343"
      url "https://github.com/stefanahman/tmux-spaces/releases/download/v#{version}/tmux-spaces_#{version}_darwin_amd64.tar.gz"
    end
  end

  name "tmux-spaces"
  desc "One config for your tmux sessions on desktop spaces"
  homepage "https://github.com/stefanahman/tmux-spaces"

  livecheck do
    skip "Auto-generated on release."
  end
  depends_on formula: [
      "tmux",
    ]

  binary "tmux-spaces"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/tmux-spaces"]
    end
  end

  # No zap stanza required
end
